name: Build and Publish Android Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Set environment variables
      run: |
        echo "GITUSERNAME=expertstack-studios" >> $GITHUB_ENV
        echo "TOKEN=***" >> $GITHUB_ENV
      shell: bash

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools-version: 33.0.2
      
    - name: Publish AAR
      run: ./gradlew publish

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download AAR
      uses: actions/download-artifact@v3
      with:
        name: android-package

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/aar/app-release.aar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
